services:
  - name: media-downloader
    ports:
      - port: 3000
        http: true
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
      - name: RATE_LIMIT_WINDOW
        value: "15"
      - name: RATE_LIMIT_MAX
        value: "100"
    regions:
      - syd
      - fra
      - nyc
    scalings:
      min: 1
      max: 3
    http_health_check:
      path: /health
      port: 3000
      interval: 10s
      timeout: 5s
      healthy_threshold: 2
      unhealthy_threshold: 3
    routes:
      - path: /
        port: 3000
    docker:
      image: koyeb/node:18
